export const SET_AUTH_DATA = 'auth/SET_AUTH_DATA'
export const CLEAR_AUTH_STATE = 'auth/CLEAR_AUTH_STATE'
export const UPDATE_AUTH_STATE = 'auth/UPDATE_AUTH_STATE'
export const SET_IS_PROCESSING = 'auth/SET_IS_PROCESSING'
export const SET_AJAX_ERROR = 'auth/SET_AJAX_ERROR'
export const SET_PHOTO = 'auth/SET_PHOTO'