export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_USERS = 'SET_USERS';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const TOGGLE_IS_FETCHING_USERS = 'TOGGLE_IS_FETCHING_USERS';
export const SET_FOLLOWING_PROCESS_USER_ID = 'SET_FOLLOWING_PROCESS_USER_ID';
